### ISSUE TITLE
How about add DynMoE to your survey?

### ISSUE THREAD

**Issue by QAQdev** [withinmiaov/A-Survey-on-Mixture-of-Experts#1]
We propose [Dynamic Mixture of Experts: An Auto-Tuning Approach for Efficient Transformer Models](https://arxiv.org/abs/2405.14297), a routing mechanism which allows for a variable number of experts per token as well as a procedure for dynamically changing the number of experts during training.

I think this may match your survey's focus! Please kindly consider including this paper.

We also provide our implementation at [LINs-lab/DynMoE](https://github.com/LINs-lab/DynMoE).

**Comment by withinmiaov** [comment]
Thanks for providing the information. We will check it out and try to include it in our revision.

**Comment by QAQdev** [comment]
Thanks a lot!
